---
- hosts: all
  vars:
    build_root: /opt
    uvcdat_install_dir: /opt/uvcdat_install
    download_testdata: ON

  tasks:
    - name: Update apt cache
      apt: update_cache=yes
      sudo: yes

    - name: Install system packages
      apt: name={{ item }} state=present
      sudo: yes
      with_items:
        - git
        - gfortran
        - g++
        - libffi-dev
        - libsqlite-dev
        - libssl-dev
        - libbz2-dev
        - libexpat-dev
        - ncurses-dev
        - curl
        - make
        - wget
        - libjpeg-dev
        - libpng-dev
        - m4
        - cmake

    - name: Clone UVCDAT source repo
      git: repo=git://github.com/UV-CDAT/uvcdat.git dest={{build_root}}/uvcdat accept_hostkey=yes version=master
      sudo: yes

    - name: Create build directory if it does not exist
      file: path={{build_root}}/uvcdat-build state=directory mode=0775
      sudo: yes

    - name: Configure UVCDAT
      command: cmake -DCDAT_BUILD_WEB=ON -DCDAT_BUILD_GUI=OFF -DCDAT_BUILD_OSMESA=ON -DCDAT_BUILD_OFFSCREEN=ON -DCMAKE_INSTALL_PREFIX={{uvcdat_install_dir}} -DCDAT_DOWNLOAD_UVCMETRICS_TESTDATA={{download_testdata}} {{build_root}}/uvcdat chdir={{build_root}}/uvcdat-build
      sudo: yes

    - name: Build UVCDAT
      command: make -j3 chdir={{build_root}}/uvcdat-build
      sudo: yes

    - name: Create script for running climatology2.py example
      template: src=run_climatology_example.sh.j2 dest={{uvcdat_install_dir}}/run_climatology_example.sh mode=0775
      sudo: yes
